### ISSUE TITLE
Bad count badge when removing a boolean filter

### ISSUE THREAD

**Issue by JoanBonnin** [degecko/nova-filters-summary#1]
Hi there. In my initial testing I've been able to detect a bug while using boolean filters.

If I remove a boolean filter from the FilterSummary card, the count badge isn't reduced by one (letting the count inconsistent). In order to actually recover the valid count, I have to mark all boolean values and re-disable them one by one.

Of course, disabling the boolean filter through the default Nova's popup gives me the expected results. 

Any clue on what could be happening here?

**Comment by degecko** [comment]
Thank you very much for reporting this issue!

When a filter was being cleared by the plugin, its value was set to an empty string. However, this was not working for boolean filters. Specifically, it didn't trigger Laravel's filter counter.

I had to update the process of clearing boolean filters by setting the filter's value to the entire list of boolean options with their values set to "false".

Please upgrade the extension to the latest version (currently 1.1.4) and it should start working properly.

**Comment by JoanBonnin** [comment]
Thanks for the quick reply and fix. Lovely
