### ISSUE TITLE
Filter always shows as active when used with popular date range filter

### ISSUE THREAD

**Issue by shstkvch** [degecko/nova-filters-summary#2]
This summary plugin is incredibly handy! But I'm using [this date filter plugin ](https://packagist.org/packages/pos-lifestyle/laravel-nova-date-range-filter) and the filter always shows as active.

This is because the filter stores its value as an array. When no date is selected, the filter value is an empty array. But nova-filters-summary still considers this to be a truthy value

**Comment by shstkvch** [comment]
PR here: https://github.com/degecko/nova-filters-summary/pull/3

**Comment by degecko** [comment]
Solution provided here: https://github.com/degecko/nova-filters-summary/pull/3#issuecomment-1154935613
